latin_name: Ocimum basilicum
common_name: Basil
family: Lamiaceae
type: herb
description: >
  Basil is a tender herb commonly used in cooking. It thrives in warm, bright conditions.

growth:
  optimal_temperature_c: [20, 30]
  photoperiod_hours: [14, 18]
  co2_ppm: 400

stages:
  - name: seedling
    duration_days: 10-20
    ppfd_umol_m2_s: [30, 80]
    recommended_dli_mol_m2_day: [2, 4]
    # Recommended red:blue ratio (red divided by blue). Values < 1 mean blue-dominant spectra.
    recommended_red_blue_ratio: [0.5, 1.0]
    notes: >
      Keep soil moist and warm for germination.

  - name: vegetative
    duration_days: 20-40
    ppfd_umol_m2_s: [150, 300]
    recommended_dli_mol_m2_day: [12, 18]
    # Favor red for leaf expansion and biomass during vegetative growth.
    recommended_red_blue_ratio: [3, 6]
    notes: >
      Increase light intensity and ensure good airflow.

  - name: mature
    duration_days: 40-60
    ppfd_umol_m2_s: [200, 400]
    recommended_dli_mol_m2_day: [18, 24]
    # Higher red fraction for finishing; promotes biomass and flowering traits.
    recommended_red_blue_ratio: [6, 12]
    notes: >
      Pinch tops to encourage bushy growth.

nutrition:
  ec_mS_cm: [1.0, 1.6]
  ph: [5.5, 6.5]

watering:
  frequency_days: 1-2
  method: drip


