latin_name: Cymbopogon citratus
common_name: Lemongrass
family: Poaceae
type: herb
description: >
  Lemongrass prefers full sun and warm conditions; it benefits from high light and steady moisture.

stages:
  - name: seedling
    duration_days: [10, 20]
    ppfd_umol_m2_s: [100, 300]
    recommended_dli_mol_m2_day: [10, 20]
    recommended_red_blue_ratio: [1.5, 3]
    co2_ppm: 400
    optimal_temperature_c: [18, 30]
    photoperiod_hours: [12, 16]
    ec_mS_cm: [1.0, 1.8]
    ph: [6.0, 7.5]
    notes: >
      Prefers warm, humid conditions and ample space to develop tall stalks.

  - name: vegetative
    duration_days: [30, 90]
    ppfd_umol_m2_s: [300, 700]
    recommended_dli_mol_m2_day: [25, 40]
    recommended_red_blue_ratio: [3, 6]
    co2_ppm: 400
    optimal_temperature_c: [20, 32]
    photoperiod_hours: [12, 16]
    ec_mS_cm: [1.2, 2.4]
    ph: [6.0, 7.5]
    notes: >
      Tall, grass-like herb; provide strong light for robust growth.

  - name: mature
    duration_days: [90, 240]
    ppfd_umol_m2_s: [400, 1000]
    recommended_dli_mol_m2_day: [30, 50]
    recommended_red_blue_ratio: [4, 8]
    co2_ppm: 400
    optimal_temperature_c: [20, 32]
    photoperiod_hours: [12, 16]
    ec_mS_cm: [1.4, 3.0]
    ph: [6.0, 7.5]
    notes: >
      Harvest stalks and leaves as needed; responds well to fertilization under high light.
