latin_name: Lactuca sativa
common_name: Lettuce
family: Asteraceae
type: leafy green
description: >
  Lettuce includes romaine, butterhead, oakleaf and leaf types. Prefers cool temperatures and moderate light to maintain tenderness and prevent bolting.

stages:
  - name: seedling
    duration_days: [7, 14]
    ppfd_umol_m2_s: [50, 150]
    recommended_dli_mol_m2_day: [6, 12]
    recommended_red_blue_ratio: [1, 3]
    co2_ppm: 400
    optimal_temperature_c: [12, 22]
    photoperiod_hours: [12, 16]
    ec_mS_cm: [0.8, 1.4]
    ph: [5.5, 6.5]
    notes: >
      Cooler temps and moderate light keep lettuce tender; higher light can increase compactness and color in some varieties.

  - name: vegetative
    duration_days: [21, 40]
    ppfd_umol_m2_s: [100, 300]
    recommended_dli_mol_m2_day: [12, 20]
    recommended_red_blue_ratio: [2, 4]
    co2_ppm: 400
    optimal_temperature_c: [12, 22]
    photoperiod_hours: [12, 16]
    ec_mS_cm: [1.0, 1.8]
    ph: [5.5, 6.5]
    notes: >
      Shade-tolerant relative; bolting risk increases with high temperatures and long days.

  - name: mature
    duration_days: [30, 70]
    ppfd_umol_m2_s: [150, 400]
    recommended_dli_mol_m2_day: [14, 25]
    recommended_red_blue_ratio: [3, 6]
    co2_ppm: 400
    optimal_temperature_c: [10, 22]
    photoperiod_hours: [12, 16]
    ec_mS_cm: [1.2, 2.0]
    ph: [5.5, 6.5]
    notes: >
      Harvest as leaf or whole head depending on type; cool storage recommended.
